export enum Screens {
  onBoarding = 'onBoarding',
  welcome = 'welcome',

  homeStack = 'homeStack',
  home = 'home',
  holdings = 'holdings',
  portfolio = 'portfolio',

  settingsStack = 'settingsStack',
  settings = 'settings',
  refer = 'refer',

  autoBuyStack = 'autoBuyStack',
  autoBuy = 'autoBuy',
  autoBuyList = 'autoBuyList',
  chooseProduct = 'chooseProduct',
  autoBuySetUp = 'autoBuySetUp',
  reviewAutoBuy = 'reviewAutoBuy',
  completeAutoBuy = 'completeAutoBuy',

  priceAlertsStack = 'priceAlertsStack',
  priceAlerts = 'priceAlerts',
  choosePriceAlert = 'choosePriceAlert',
  priceAlertSetUp = 'priceAlertSetUp',

  signUp = 'signUp',
  introduce = 'introduce',
  email = 'email',
  password = 'password',
  emailVerification = 'emailVerification',
  emailVerSuccess = 'emailVerSuccess',
  emailVerError = 'emailVerError',
  mobileVerification = 'mobileVerification',
  mobileVerCode = 'mobileVerCode',
  mobileVerSuccess = 'mobileVerSuccess',

  signIn = 'signIn',
  logIn = 'logIn',
  forgotPassword = 'forgotPassword',
  forgotPassSucces = 'forgotPassSucces',
  forgotPassError = 'ForgotPassError',
  forgotPassDone = 'forgotPassDone',
  mobileLogInCode = 'mobileLogInCode',
}
