export enum Screens {
  onBoarding = 'onBoarding',
  welcome = 'welcome',
  signUp = 'signUp',
  signIn = 'signIn',
  introduce = 'introduce',
  email = 'email',
  password = 'password',
  emailVerification = 'emailVerification',
  emailVerSuccess = 'emailVerSuccess',
  emailVerError = 'emailVerError',
  mobileVerification = 'mobileVerification',
  mobileVerCode = 'mobileVerCode',
  mobileVerSuccess = 'mobileVerSuccess',
  logIn = 'logIn',
  forgotPassword = 'forgotPassword',
  forgotPassSucces = 'forgotPassSucces',
  forgotPassError = 'ForgotPassError',
  forgotPassDone = 'forgotPassDone',
}
