export const activity = [
  {
    type: 'Bought Platinum',
    date: 'May 7, 2021',
    color: '#135D2D',
    usd: '+ $5.45',
    oz: '0.002 oz',
    image: require('../assets/images/home/buy.png'),
    id: '1',
  },
  {
    type: 'Sold Platinum',
    date: 'May 7, 2021',
    color: '#135D2D',
    usd: '+ $7.80',
    oz: '0.003 oz',
    image: require('../assets/images/home/sold.png'),
    id: '2',
  },
  {
    type: 'Deposited Cash',
    date: 'May 7, 2021',
    color: '#135D2D',
    usd: '+ $28.45',
    image: require('../assets/images/home/deposit.png'),
    id: '3',
  },
  {
    type: 'Redeemed Products F...',
    date: 'May 7, 2021',
    color: '#135D2D',
    usd: '+ $4.12',
    image: require('../assets/images/home/redeemed.png'),
    id: '4',
  },
  {
    type: 'Withdrawn cash',
    date: 'May 7, 2021',
    color: '#A01313',
    usd: '- $17.00',
    image: require('../assets/images/home/withdrawn.png'),
    id: '5',
  },
];
