export * from './slides';
export * from './passwordConditions';
export * from './metals';
export * from './activity';
export * from './news';
export * from './time';
export * from './autoBuy';
export * from './states';
export * from './cookieLinks';

export * from './getNextYear';
export * from './getColor';
export * from './getMetalImage';
export * from './cardNumberValidation';
export * from './getPaymentImage';
export * from './setExpiring';
export * from './setCard';
export * from './getCardImage';
export * from './getCardType';
